/**
 * Types for AI-powered migrations
 */

/**
 * Represents a file edit generated by the AI
 */
export interface IFileEdit {
  /** Relative path from repository root */
  path: string;
  /** Type of edit operation */
  action: 'create' | 'modify' | 'delete';
  /** New content for create/modify operations */
  content?: string;
}

/**
 * Response from AI provider after generating edits
 */
export interface IAIResponse {
  /** List of file edits to apply */
  edits: IFileEdit[];
  /** Optional explanation of changes made */
  explanation?: string;
  /** Number of tokens used (if available) */
  tokensUsed?: number;
}

/**
 * Request to AI provider for generating edits
 */
export interface IAIRequest {
  /** The migration prompt/instruction */
  prompt: string;
  /** Files from the repository to analyze */
  files: IFileContent[];
  /** Path to the repository directory */
  repoDir: string;
  /** AI model to use (provider-specific) */
  model?: string;
  /** Maximum tokens for response */
  maxTokens?: number;
  /** Custom API base URL (for local models or proxies) */
  baseUrl?: string;
}

/**
 * File content read from repository
 */
export interface IFileContent {
  /** Relative path from repository root */
  path: string;
  /** File content as string */
  content: string;
}

/**
 * AI configuration from shepherd.yml or CLI
 */
export interface IAIConfig {
  /** AI provider: 'claude', 'openai', or 'ollama' */
  provider: string;
  /** Model identifier (provider-specific) */
  model?: string;
  /** The migration prompt */
  prompt: string;
  /** File filtering configuration */
  context?: {
    /** Glob patterns for files to include */
    include?: string[];
    /** Glob patterns for files to exclude */
    exclude?: string[];
  };
  /** Maximum tokens for AI response */
  max_tokens?: number;
  /** Custom API base URL (for local models or proxies) */
  baseUrl?: string;
}
